// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpwk5rv7jAZcTWsm5lPeobwQYqko9pO2w',
    appId: '1:81379324972:web:9faf53c6afefd2190ccd89',
    messagingSenderId: '81379324972',
    projectId: 'foodgo-46336',
    authDomain: 'foodgo-46336.firebaseapp.com',
    storageBucket: 'foodgo-46336.firebasestorage.app',
    measurementId: 'G-8XCESMFVSE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADl40C79hZGWItZ3dVU3-qNsBZcrZtoeU',
    appId: '1:81379324972:android:55e2199094fe6c0e0ccd89',
    messagingSenderId: '81379324972',
    projectId: 'foodgo-46336',
    storageBucket: 'foodgo-46336.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbnRJblxaOAD_Pk-fTWJe4uXOuthQxU-c',
    appId: '1:81379324972:ios:99f33689e2a331c40ccd89',
    messagingSenderId: '81379324972',
    projectId: 'foodgo-46336',
    storageBucket: 'foodgo-46336.firebasestorage.app',
    iosBundleId: 'com.example.foodGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpwk5rv7jAZcTWsm5lPeobwQYqko9pO2w',
    appId: '1:81379324972:web:9a09432491c192180ccd89',
    messagingSenderId: '81379324972',
    projectId: 'foodgo-46336',
    authDomain: 'foodgo-46336.firebaseapp.com',
    storageBucket: 'foodgo-46336.firebasestorage.app',
    measurementId: 'G-4MFWVNM426',
  );
}
